name: MinecraftAdvancementSync
version: '${project.version}'
main: com.comorichico.minecraftadvancementsync.MinecraftAdvancementSync
api-version: '1.20'
commands:
  mas:
    description: Execute FTPSUploader to upload file